#if !defined(AFX__SUBWIZARD_H__7E5CD61B_297E_433B_9C24_6182E8F6C298__INCLUDED_)
#define AFX__SUBWIZARD_H__7E5CD61B_297E_433B_9C24_6182E8F6C298__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// C_SubWizard wrapper class

class C_SubWizard : public CWnd
{
protected:
	DECLARE_DYNCREATE(C_SubWizard)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xd5288403, 0xe6c5, 0x11d1, { 0xbe, 0x7d, 0xc6, 0x38, 0x15, 0x0, 0x0, 0x0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__SUBWIZARD_H__7E5CD61B_297E_433B_9C24_6182E8F6C298__INCLUDED_)
