// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "_subwizard.h"

/////////////////////////////////////////////////////////////////////////////
// C_SubWizard

IMPLEMENT_DYNCREATE(C_SubWizard, CWnd)

/////////////////////////////////////////////////////////////////////////////
// C_SubWizard properties

/////////////////////////////////////////////////////////////////////////////
// C_SubWizard operations
