#if !defined(AFX_HISTCURVE_H__616F0CF2_8F4B_454A_98E3_6B0E966669F2__INCLUDED_)
#define AFX_HISTCURVE_H__616F0CF2_8F4B_454A_98E3_6B0E966669F2__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CHistCurve wrapper class

class CHistCurve : public CWnd
{
protected:
	DECLARE_DYNCREATE(CHistCurve)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xe6908186, 0x7498, 0x11d7, { 0xa8, 0x15, 0x0, 0x1, 0x1, 0xc6, 0x1d, 0x9f } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetCaption();
	void SetCaption(LPCTSTR);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	short GetBorderStyle();
	void SetBorderStyle(short);

// Operations
public:
	long AddPoint(double f8Value);
	double SetYScal(double f8YScal);
	void SetBufferSize(long iBufferSize);
	void SetEraseColor(short ucRed, short ucGreen, short ucBlue);
	void SetCurveColor(short ucRed, short ucGreen, short ucBlue);
	BOOL ExtractData(double* pf8Value, long iNum);
	long GetBufferSize();
	double GetYScal();
	double GetFirstPoint();
	void SetYZeroValue(double f8YZeroValue);
	long GetEraseColor();
	long GetCurveColor();
	double GetYZero();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_HISTCURVE_H__616F0CF2_8F4B_454A_98E3_6B0E966669F2__INCLUDED_)
